const languages = {
  "en": {
    "account": "Account",
    "to-cart": "Add to Cart",
    "cart": "Cart",
    "login": "Login",
    "logout": "Logout",
    "register": "Register",
    "your-games": "Your games",
    "library": "Library",
    "purchase": "Buy",
    "tags": "Tags",
    "price-range": "Price range",
    "project-member": "Project members",
    "recommended": "Recommended",
    "notlogin": "Please log in before adding to cart",
    "alreadyhasgameincart": "Selected game is already in cart",
    "alreadyhasgameinlibrary": "Selected game is already in library",
    "homePage": "Home",
    "languageChangeMobileNavBar": "Lang",
    "boughtGameAddedToLibrary": "Games added to library!",
    "redirectingToLibrary": "Returning to library...",

  },
  "th": {
    "account": "บัญชี",
    "to-cart": "หยิบใส่ตะกร้า",
    "cart": "ตะกร้า",
    "login": "ล็อกอิน",
    "logout": "ล็อกเอาท์",
    "register": "สมัครสมาชิก",
    "your-games": "เกมของคุณ",
    "library": "คลังเกม",
    "purchase": "ซื้อ",
    "tags": "ประเภทเกม",
    "price-range": "ราคา",
    "project-member": "รายชื่อผู้จัดทำ",
    "recommended": "เกมแนะนำ",
    "notlogin": "กรุณาลงชื่อล็อกอิน",
    "alreadyhasgameincart": "เกมที่ท่านเลือกมีอยู่ในตระกร้าอยู่แล้ว",
    "alreadyhasgameinlibrary": "เกมที่ท่านเลือกมีอยู่ในคลังอยู่แล้ว",
    "homePage": "หน้าแรก",
    "languageChangeMobileNavBar": "ภาษา",
    "boughtGameAddedToLibrary": "เพิ่มเข้าไปในคลังเกมแล้ว!",
    "redirectingToLibrary": "กำลังกลับไปยังคลังเกม...",
  }
}

export default languages